name: Deploy to Supabase

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "🚀 Deploying to Staging Environment"
          supabase link --project-ref ${{ secrets.STAGING_PROJECT_REF }} --password ${{ secrets.STAGING_DB_PASSWORD }}
          supabase db push --password ${{ secrets.STAGING_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🚀 Deploying to Production Environment"
          echo "⚠️  Production deployment - Project: zutbqmhxvdgvcllobtxo"
          supabase link --project-ref ${{ secrets.PRODUCTION_PROJECT_REF }} --password ${{ secrets.PRODUCTION_DB_PASSWORD }}
          supabase db push --password ${{ secrets.PRODUCTION_DB_PASSWORD }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}